// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MOCA_Repositories.Enitities;

public partial class DoctorProfile
{
    public int DoctorId { get; set; }

    public string FullName { get; set; }

    public string Specialization { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public virtual ICollection<DoctorBooking> DoctorBookings { get; set; } = new List<DoctorBooking>();

    public virtual ICollection<DoctorContact> DoctorContacts { get; set; } = new List<DoctorContact>();
}