// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MOCA_Repositories.Enitities;

public partial class Lesson
{
    public int LessonId { get; set; }

    public int? ChapterId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string VideoUrl { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? Duration { get; set; }

    public int? OrderIndex { get; set; }

    public string Status { get; set; }

    public virtual Chapter Chapter { get; set; }
}