// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MOCA_Repositories.Enitities;

public partial class RefLect
{
    public int RefLectId { get; set; }

    public int? UserId { get; set; }

    public int? CourseId { get; set; }

    public DateOnly? RefDate { get; set; }

    public string Status { get; set; }

    public virtual Course Course { get; set; }

    public virtual User User { get; set; }
}