// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MOCA_Repositories.Enitities;

public partial class User
{
    public int UserId { get; set; }

    public int? RoleId { get; set; }

    public string FullName { get; set; }


    public string Email { get; set; }

    public string Password { get; set; }

    public string PhoneNumber { get; set; }

    public string Image { get; set; }

    public string Status { get; set; }

    public virtual ICollection<CommunityPost> CommunityPosts { get; set; } = new List<CommunityPost>();

    public virtual ICollection<CommunityReply> CommunityReplies { get; set; } = new List<CommunityReply>();

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    public virtual ICollection<DoctorBooking> DoctorBookings { get; set; } = new List<DoctorBooking>();

    public virtual ICollection<DoctorContact> DoctorContacts { get; set; } = new List<DoctorContact>();

    public virtual MomProfile MomProfile { get; set; }

    public virtual ICollection<PostLike> PostLikes { get; set; } = new List<PostLike>();

    public virtual ICollection<PurchasePackage> PurchasePackages { get; set; } = new List<PurchasePackage>();

    public virtual ICollection<PurchasedCourse> PurchasedCourses { get; set; } = new List<PurchasedCourse>();

    public virtual ICollection<RefLect> RefLects { get; set; } = new List<RefLect>();

    public virtual Role Role { get; set; }

    public virtual ICollection<UserPregnancy> UserPregnancies { get; set; } = new List<UserPregnancy>();
}