// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MOCA_Repositories.Enitities;

public partial class BabyTracking
{
    public int CheckupBabyId { get; set; }

    public int? PregnancyId { get; set; }

    public DateOnly? CheckupDate { get; set; }

    public int? FetalHeartRate { get; set; }

    public decimal? EstimatedWeight { get; set; }

    public decimal? AmnioticFluidIndex { get; set; }

    public string PlacentaPosition { get; set; }

    public string DoctorComment { get; set; }

    public string UltrasoundImage { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual UserPregnancy Pregnancy { get; set; }
}