// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MOCA_Repositories.Enitities;

public partial class MessagesWithDoctor
{
    public int MessageId { get; set; }

    public int? ContactId { get; set; }

    public string SenderType { get; set; }

    public string MessageText { get; set; }

    public DateTime? SendAt { get; set; }

    public virtual DoctorContact Contact { get; set; }
}