// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MOCA_Repositories.Enitities;

public partial class PurchasePackage
{
    public int PurchasePackageId { get; set; }

    public int? PackageId { get; set; }

    public int? UserId { get; set; }

    public DateTime? PurchaseDate { get; set; }

    public string Status { get; set; }

    public int? DiscountId { get; set; }

    public virtual Discount Discount { get; set; }

    public virtual Package Package { get; set; }

    public virtual User User { get; set; }
}